In [ ]:
import torch

print("PyTorch version:", torch.__version__)
print("CUDA available:", torch.cuda.is_available())
print("CUDA version:", torch.version.cuda)
if torch.cuda.is_available():
    print("GPU device:", torch.cuda.get_device_name(0))
    print("Number of GPUs:", torch.cuda.device_count())

In [1]:
import os
import sys

sys.path.append(os.path.abspath(".."))

from models.base import ModelConfig
from models.deepseekvl2tiny import DeepSeekVl2Tiny

model_path = "deepseek-ai/deepseek-vl2-tiny"


cfg = ModelConfig.from_dict({
    "name": "deepseekvl2tiny",
    "model_name": "deepseek-vl2-tiny",
    "model_path": model_path,
    "max_new_tokens": 512,
    "temperature": 0,
    "device": "cuda",
    "device_map": "auto",
    "dtype": "bfloat16",
})

model = DeepSeekVl2Tiny(cfg)

Python version is above 3.10, patching the collections module.
[LOGS] Loading DeepSeek-VL2-Tiny from deepseek-ai/deepseek-vl2-tiny...
[LOGS] Loading processor...

C:\Users\marvi\miniconda3\envs\pytorch_cuda\Lib\site-packages\huggingface_hub\file_download.py:945: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.

Add pad token = ['<｜▁pad▁｜>'] to the tokenizer
<｜▁pad▁｜>:2
Add image token = ['<image>'] to the tokenizer
<image>:128815
Add grounding-related tokens = ['<|ref|>', '<|/ref|>', '<|det|>', '<|/det|>', '<|grounding|>'] to the tokenizer with input_ids
<|ref|>:128816
<|/ref|>:128817
<|det|>:128818
<|/det|>:128819
<|grounding|>:128820
Add chat tokens = ['<|User|>', '<|Assistant|>'] to the tokenizer with input_ids
<|User|>:128821
<|Assistant|>:128822

[LOGS] Loading model...
[LOGS] DeepSeek-VL2-Tiny loaded successfully on cuda

In [2]:
import pandas as pd

day_path = 'F:\SynDORBench\index\human_detection\day.jsonl'
day_df = pd.read_json(day_path, lines=True)

print(day_df.loc[0, 'img_path'])
from pathlib import Path

time_instruction = f"This is 1 video frame from from a surveillance footage."

perspective_prompt = "You are seeing this image from a surveillance camera view and you are the surveillance camera. What action is the person performing?"
task_prompt = "Describe in details what you see from the video frame."

dataset_dir = Path("F:/SynDORBench")
picture_path = Path(
    "images/SMPLitex_texture_00000_choking_huge_landscape_noon_south_10.8/run_pose-06-hangon-kaiwa_stageii_frame_780.npz_20250907_220206/raw_images/frame0001_cam000_r10_phi0.0_theta0.0.jpg")

abs_picture_path = dataset_dir / picture_path

actual_path = 'F:/SynDORBench/images/SMPLitex_texture_00000_choking_huge_landscape_noon_south_10.8/run_pose-06-hangon-kaiwa_stageii_frame_780.npz_20250907_220206/raw_images/frame0001_cam000_r10_phi0.0_theta0.0.jpg'

print(actual_path)
print(str(abs_picture_path))
print(actual_path == str(abs_picture_path))

base_text = f"\n{time_instruction}\n{perspective_prompt} {task_prompt}"

print(model.predict(actual_path, base_text))

You're using a LlamaTokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.

images/SMPLitex_texture_00000_choking_huge_landscape_noon_south_10.8/run_pose-06-hangon-kaiwa_stageii_frame_780.npz_20250907_220206/raw_images/frame0001_cam000_r10_phi0.0_theta0.0.jpg
F:/SynDORBench/images/SMPLitex_texture_00000_choking_huge_landscape_noon_south_10.8/run_pose-06-hangon-kaiwa_stageii_frame_780.npz_20250907_220206/raw_images/frame0001_cam000_r10_phi0.0_theta0.0.jpg
F:\SynDORBench\images\SMPLitex_texture_00000_choking_huge_landscape_noon_south_10.8\run_pose-06-hangon-kaiwa_stageii_frame_780.npz_20250907_220206\raw_images\frame0001_cam000_r10_phi0.0_theta0.0.jpg
False
The person appears to be standing still with their arms at their sides. They seem to be facing forward towards the camera, which suggests they might be observing something or someone in front of them. The exact nature of their activity cannot be determined solely based on this single frame without additional context or information about the surrounding environment.The image provided is a video frame from a surveillance camera. The person in the video frame appears to be standing still with their arms at their sides. They seem to be facing forward towards the camera. The background of the video frame shows an outdoor setting with some greenery visible behind them. There's no clear indication of any specific actions being performed by the individual within this particular frame.

Based on the information available in the image, it seems that the person might be engaged in observing something or someone outside the frame, possibly monitoring activities around them. However, without more context or additional frames, we cannot definitively determine the exact nature of their activity.The image provided is a video frame from a surveillance camera. The person in the video frame appears to be standing still with their arms at their sides. They seem to be facing forward towards the camera. The background of the video frame shows an outdoor setting with some greenery visible behind them. There's no clear indication of any specific actions being performed by the individual within this particular frame.

Based on the information available in the image, it seems that the person might be observing something or someone outside the frame. However, without more context or additional frames, we cannot definitively determine the exact nature of their activity.The image provided is a video frame from a surveillance camera. The person in the video frame appears to be standing still with their arms at their sides. They seem to be facing forward towards the camera. The background of the video frame shows an outdoor setting with some greenery visible behind them. There's no clear indication of any specific actions being performed by the individual within this particular frame.

Based on the information available in the image, it seems that the person might be observing something or someone outside the frame. However, without more context or additional frames, we cannot definitively determine the exact nature of their activity.The image provided is a video frame from a surveillance camera. The person in the video frame appears to be standing still with their arms at their sides. They seem to be facing forward towards the camera. The background of the video frame shows an outdoor setting with some greenery visible behind them. There's no clear indication of any specific actions being performed by the

In [3]:
day_df.head()

,source_dir,action,scene,lighting,radius,smplx_texture,img_path,mask_path,img_name,nv_path,human_discernable,prompt,task
0,SMPLitex_texture_00000_choking_huge_landscape_...,choking,huge_landscape,noon_south,10.8,SMPLitex-texture-00000,images/SMPLitex_texture_00000_choking_huge_lan...,images/SMPLitex_texture_00000_choking_huge_lan...,frame0001_cam000_r10_phi0.0_theta0.0.jpg,NaN,1,Respond only with 1 or 0. Respond with 1 if a ...,human_detection
1,SMPLitex_texture_00000_choking_huge_landscape_...,choking,huge_landscape,noon_south,10.8,SMPLitex-texture-00000,images/SMPLitex_texture_00000_choking_huge_lan...,images/SMPLitex_texture_00000_choking_huge_lan...,frame0001_cam001_r10_phi0.0_theta22.5.jpg,NaN,1,Respond only with 1 or 0. Respond with 1 if a ...,human_detection
2,SMPLitex_texture_00000_choking_huge_landscape_...,choking,huge_landscape,noon_south,10.8,SMPLitex-texture-00000,images/SMPLitex_texture_00000_choking_huge_lan...,images/SMPLitex_texture_00000_choking_huge_lan...,frame0001_cam002_r10_phi0.0_theta45.0.jpg,NaN,1,Respond only with 1 or 0. Respond with 1 if a ...,human_detection
3,SMPLitex_texture_00000_choking_huge_landscape_...,choking,huge_landscape,noon_south,10.8,SMPLitex-texture-00000,images/SMPLitex_texture_00000_choking_huge_lan...,images/SMPLitex_texture_00000_choking_huge_lan...,frame0001_cam003_r10_phi0.0_theta67.5.jpg,NaN,1,Respond only with 1 or 0. Respond with 1 if a ...,human_detection
4,SMPLitex_texture_00000_choking_huge_landscape_...,choking,huge_landscape,noon_south,10.8,SMPLitex-texture-00000,images/SMPLitex_texture_00000_choking_huge_lan...,images/SMPLitex_texture_00000_choking_huge_lan...,frame0001_cam004_r10_phi45.0_theta0.0.jpg,NaN,1,Respond only with 1 or 0. Respond with 1 if a ...,human_detection

In [4]:
def get_inference_from_df(model, df, root_dir="", limit=5):
    results = []

    # for prototyping, limit to head
    if limit:
        df = df.head(limit)

    for i in range(len(df)):
        img_path = df.loc[i, 'img_path']
        task_prompt = df.loc[i, 'prompt']
        if root_dir:
            img_path = root_dir / img_path

        pred = model.predict(img_path, task_prompt)


        results.append({
            "img_path": img_path,
            "task_prompt": task_prompt,
            "prediction": pred
        })
    return pd.DataFrame(results)


small_df = day_df.head(100)
result_df = get_inference_from_df(model, small_df, root_dir=dataset_dir)

In [5]:
result_df

,img_path,task_prompt,prediction
0,F:\SynDORBench\images\SMPLitex_texture_00000_c...,Respond only with 1 or 0. Respond with 1 if a ...,1
1,F:\SynDORBench\images\SMPLitex_texture_00000_c...,Respond only with 1 or 0. Respond with 1 if a ...,1
2,F:\SynDORBench\images\SMPLitex_texture_00000_c...,Respond only with 1 or 0. Respond with 1 if a ...,1
3,F:\SynDORBench\images\SMPLitex_texture_00000_c...,Respond only with 1 or 0. Respond with 1 if a ...,1
4,F:\SynDORBench\images\SMPLitex_texture_00000_c...,Respond only with 1 or 0. Respond with 1 if a ...,1