In [ ]:
import os
import sys

sys.path.append(os.path.abspath(".."))

from models.base import ModelConfig
from models.llava_action import LLavaAction

model_path = "/mnt/harddisk/jeremy/models/MLAdaptiveIntelligence/LLaVAction-7B"


cfg = ModelConfig.from_dict({
    "model_name": "llava_qwen",
    "model_path": model_path,  # or local path
    "max_new_tokens": 512,
    "temperature": 0,
    "device": "cuda",
    "device_map": {"": "cuda"},
    "dtype": "bfloat16",
    # "quantization_config": BitsAndBytesConfig(load_in_8bit=True),
})

model = LLavaAction(cfg)

/home/jeremy/code/SynDORBench/syndorb_env/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Please install pyav to use video processing functions.

/home/jeremy/code/SynDORBench/syndorb_env/lib/python3.10/site-packages/huggingface_hub/file_download.py:945: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: c2109339-2148-46b2-accb-37a43207f687)')' thrown while requesting HEAD https://huggingface.co/meta-llama/Meta-Llama-3-8B-Instruct/resolve/main/tokenizer_config.json
Retrying in 1s [Retry 1/5].

Loaded LLaVA model: /mnt/harddisk/jeremy/models/MLAdaptiveIntelligence/LLaVAction-7B

Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
You are using a model of type qwen2 to instantiate a model of type llava_qwen. This is not supported for all configurations of models and can yield errors.

Loading vision tower: google/siglip-so400m-patch14-384

/home/jeremy/code/SynDORBench/syndorb_env/lib/python3.10/site-packages/torch/nn/modules/module.py:2441: UserWarning: for vision_model.embeddings.patch_embedding.weight: copying from a non-meta parameter in the checkpoint to a meta parameter in the current model, which is a no-op. (Did you mean to pass `assign=True` to assign items in the state dictionary to their corresponding key in the module instead of copying them in place?)
  warnings.warn(
/home/jeremy/code/SynDORBench/syndorb_env/lib/python3.10/site-packages/torch/nn/modules/module.py:2441: UserWarning: for vision_model.embeddings.patch_embedding.bias: copying from a non-meta parameter in the checkpoint to a meta parameter in the current model, which is a no-op. (Did you mean to pass `assign=True` to assign items in the state dictionary to their corresponding key in the module instead of copying them in place?)
  warnings.warn(
/home/jeremy/code/SynDORBench/syndorb_env/lib/python3.10/site-packages/torch/nn/modules/module.py:2441: UserWarning: for vision_model.embeddings.position_embedding.weight: copying from a non-meta parameter in the checkpoint to a meta parameter in the current model, which is a no-op. (Did you mean to pass `assign=True` to assign items in the state dictionary to their corresponding key in the module instead of copying them in place?)
  warnings.warn(
/home/jeremy/code/SynDORBench/syndorb_env/lib/python3.10/site-packages/torch/nn/modules/module.py:2441: UserWarning: for vision_model.encoder.layers.0.self_attn.k_proj.weight: copying from a non-meta parameter in the checkpoint to a meta parameter in the current model, which is a no-op. (Did you mean to pass `assign=True` to assign items in the state dictionary to their corresponding key in the module instead of copying them in place?)
  warnings.warn(
/home/jeremy/code/SynDORBench/syndorb_env/lib/python3.10/site-packages/torch/nn/modules/module.py:2441: UserWarning: for vision_model.encoder.layers.0.self_attn.k_proj.bias: copying from a non-meta parameter in the checkpoint to a meta parameter in the current model, which is a no-op. (Did you mean to pass `assign=True` to assign items in the state dictionary to their corresponding key in the module instead of copying them in place?)
  warnings.warn(
/home/jeremy/code/SynDORBench/syndorb_env/lib/python3.10/site-packages/torch/nn/modules/module.py:2441: UserWarning: for vision_model.encoder.layers.0.self_attn.v_proj.weight: copying from a non-meta parameter in the checkpoint to a meta parameter in the current model, which is a no-op. (Did you mean to pass `assign=True` to assign items in the state dictionary to their corresponding key in the module instead of copying them in place?)
  warnings.warn(
/home/jeremy/code/SynDORBench/syndorb_env/lib/python3.10/site-packages/torch/nn/modules/module.py:2441: UserWarning: for vision_model.encoder.layers.0.self_attn.v_proj.bias: copying from a non-meta parameter in the checkpoint to a meta parameter in the current model, which is a no-op. (Did you mean to pass `assign=True` to assign items in the state dictionary to their corresponding key in the module instead of copying them in place?)
  warnings.warn(
/home/jeremy/code/SynDORBench/syndorb_env/lib/python3.10/site-packages/torch/nn/modules/module.py:2441: UserWarning: for vision_model.encoder.layers.0.self_attn.q_proj.weight: copying from a non-meta parameter in the checkpoint to a meta parameter in the current model, which is a no-op. (Did you mean to pass `assign=True` to assign items in the state dictionary to their corresponding key in the module instead of copying them in place?)
  warnings.warn(
/home/jeremy/code/SynDORBench/syndorb_env/lib/python3.10/site-packages/torch/nn/modules/module.py:2441: UserWarning: for vision_model.encoder.layers.0.self_attn.q_proj.bias: copying from a non-meta parameter in the checkpoint to a meta parameter in the current model, which is a no-op. (Did you mean to pass `assign=True` to assign items in the state dictionary to their corresponding key in the module instead of copying them in place?)
  warnings.warn(
/home/jeremy/code/SynDORBench/syndorb_env/lib/python3.10/site-packages/torch/nn/modules/module.py:2441: UserWarning: for vision_model.encoder.layers.0.self_attn.out_proj.weight: copying from a non-meta parameter in the checkpoint to a meta parameter in the current model, which is a no-op. (Did you mean to pass `assign=True` to assign items in the state dictionary to their corresponding key in the module instead of copying them in place?)
  warnings.warn(
/home/jeremy/code/SynDORBench/syndorb_env/lib/python3.10/site-packages/torch/nn/modules/module.py:2441: UserWarning: for vision_model.encoder.layers.0.self_attn.out_proj.bias: copying from a non-meta parameter in the checkpoint to a meta parameter in the current model, which is a no-op. (Did you mean to pass `assign=True` to assign items in the state dictionary to their corresponding key in the module instead of copying them in place?)
  warnings.warn(
/home/jeremy/code/SynDORBench/syndorb_env/lib/python3.10/site-packages/torch/nn/modules/module.py:2441: UserWarning: for vision_model.encoder.layers.0.layer_norm1.weight: copying from a non-meta parameter in the checkpoint to a meta parameter in the current model, which is a no-op. (Did you mean to pass `assign=True` to assign items in the state dictionary to their corresponding key in the module instead of copying them in place?)
  warnings.warn(
/home/jeremy/code/SynDORBench/syndorb_env/lib/python3.10/site-packages/torch/nn/modules/module.py:2441: UserWarning: for vision_model.encoder.layers.0.layer_norm1.bias: copying from a non-meta parameter in the checkpoint to a meta parameter in the current model, which is a no-op. (Did you mean to pass `assign=True` to assign items in the state dictionary to their corresponding key in the module instead of copying them in place?)
  warnings.warn(
/home/jeremy/code/SynDORBench/syndorb_env/lib/python3.10/site-packages/torch/nn/modules/module.py:2441: UserWarning: for vision_model.encoder.layers.0.mlp.fc1.weight: copying from a non-meta parameter in the checkpoint to a meta parameter in the current model, which is a no-op. (Did you mean to pass `assign=True` to assign items in the state dictionary to their corresponding key in the module instead of copying them in place?)
  warnings.warn(
/home/jeremy/code/SynDORBench/syndorb_env/lib/python3.10/site-packages/torch/nn/modules/module.py:2441: UserWarning: for vision_model.encoder.layers.0.mlp.fc1.bias: copying from a non-meta parameter in the checkpoint to a meta parameter in the current model, which is a no-op. (Did you mean to pass `assign=True` to assign items in the state dictionary to their corresponding key in the module instead of copying them in place?)
  warnings.warn(
/home/jeremy/code/SynDORBench/syndorb_env/lib/python3.10/site-packages/torch/nn/modules/module.py:2441: UserWarning: for vision_model.encoder.layers.0.mlp.fc2.weight: copying from a non-meta parameter in the checkpoint to a meta parameter in the current model, which is a no-op. (Did you mean to pass `assign=True` to assign items in the state dictionary to their corresponding key in the module instead of copying them in place?)
  warnings.warn(
/home/jeremy/code/SynDORBench/syndorb_env/lib/python3.10/site-packages/torch/nn/modules/module.py:2441: UserWarning: for vision_model.encoder.layers.0.mlp.fc2.bias: copying from a non-meta parameter in the checkpoint to a meta parameter in the current model, which is a no-op. (Did you mean to pass `assign=True` to assign items in the state dictionary to their corresponding key in the module instead of copying them in place?)
  warnings.warn(
/home/jeremy/code/SynDORBench/syndorb_env/lib/python3.10/site-packages/torch/nn/modules/module.py:2441: UserWarning: for vision_model.encoder.layers.0.layer_norm2.weight: copying from a non-meta parameter in the checkpoint to a meta parameter in the current model, which is a no-op. (Did you mean to pass `assign=True` to assign items in the state dictionary to their corresponding key in the module instead of copying them in place?)
  warnings.warn(
/home/jeremy/code/SynDORBench/syndorb_env/lib/python3.10/site-packages/torch/nn/modules/module.py:2441: UserWarning: for vision_model.encoder.layers.0.layer_norm2.bias: copying from a non-meta parameter in the checkpoint to a meta parameter in the current model, which is a no-op. (Did you mean to pass `assign=True` to assign items in the state dictionary to their corresponding key in the module instead of copying them in place?)
  warnings.warn(
/home/jeremy/code/SynDORBench/syndorb_env/lib/python3.10/site-packages/torch/nn/modules/module.py:2441: UserWarning: for vision_model.encoder.layers.1.self_attn.k_proj.weight: copying from a non-meta parameter in the checkpoint to a meta parameter in the current model, which is a no-op. (Did you mean to pass `assign=True` to assign items in the state dictionary to their corresponding key in the module instead of copying them in place?)
  warnings.warn(
/home/jeremy/code/SynDORBench/syndorb_env/lib/python3.10/site-packages/torch/nn/modules/module.py:2441: UserWarning: for vision_model.encoder.layers.1.self_attn.k_proj.bias: copying from a non-meta parameter in the checkpoint to a meta parameter in the current model, which is a no-op. (Did you mean to pass `assign=True` to assign items in the state dictionary to their corresponding key in the module instead of copying them in place?)
  warnings.warn(
/home/jeremy/code/SynDORBench/syndorb_env/lib/python3.10/site-packages/torch/nn/modules/module.py:2441: UserWarning: for vision_model.encoder.layers.1.self_attn.v_proj.weight: copying from a non-meta parameter in the checkpoint to a meta parameter in the current model, which is a no-op. (Did you mean to pass `assign=True` to assign items in the state dictionary to their corresponding key in the module instead of copying them in place?)
  warnings.warn(
/home/jeremy/code/SynDORBench/syndorb_env/lib/python3.10/site-packages/torch/nn/modules/module.py:2441: UserWarning: for vision_model.encoder.layers.1.self_attn.v_proj.bias: copying from a non-meta parameter in the checkpoint to a meta parameter in the current model, which is a no-op. (Did you mean to pass `assign=True` to assign items in the state dictionary to their corresponding key in the module instead of copying them in place?)
  warnings.warn(
/home/jeremy/code/SynDORBench/syndorb_env/lib/python3.10/site-packages/torch/nn/modules/module.py:2441: UserWarning: for vision_model.encoder.layers.1.self_attn.q_proj.weight: copying from a non-meta parameter in the checkpoint to a meta parameter in the current model, which is a no-op. (Did you mean to pass `assign=True` to assign items in the state dictionary to their corresponding key in the module instead of copying them in place?)
  warnings.warn(
/home/jeremy/code/SynDORBench/syndorb_env/lib/python3.10/site-packages/torch/nn/modules/module.py:2441: UserWarning: for vision_model.encoder.layers.1.self_attn.q_proj.bias: copying from a non-meta parameter in the checkpoint to a meta parameter in the current model, which is a no-op. (Did you mean to pass `assign=True` to assign items in the state dictionary to their corresponding key in the module instead of copying them in place?)
  warnings.warn(
/home/jeremy/code/SynDORBench/syndorb_env/lib/python3.10/site-packages/torch/nn/modules/module.py:2441: UserWarning: for vision_model.encoder.layers.1.self_attn.out_proj.weight: copying from a non-meta parameter in the checkpoint to a meta parameter in the current model, which is a no-op. (Did you mean to pass `assign=True` to assign items in the state dictionary to their corresponding key in the module instead of copying them in place?)
  warnings.warn(
/home/jeremy/code/SynDORBench/syndorb_env/lib/python3.10/site-packages/torch/nn/modules/module.py:2441: UserWarning: for vision_model.encoder.layers.1.self_attn.out_proj.bias: copying from a non-meta parameter in the checkpoint to a meta parameter in the current model, which is a no-op. (Did you mean to pass `assign=True` to assign items in the state dictionary to their corresponding key in the module instead of copying them in place?)
  warnings.warn(
/home/jeremy/code/SynDORBench/syndorb_env/lib/python3.10/site-packages/torch/nn/modules/module.py:2441: UserWarning: for vision_model.encoder.layers.1.layer_norm1.weight: copying from a non-meta parameter in the checkpoint to a meta parameter in the current model, which is a no-op. (Did you mean to pass `assign=True` to assign items in the state dictionary to their corresponding key in the module instead of copying them in place?)
  warnings.warn(
/home/jeremy/code/SynDORBench/syndorb_env/lib/python3.10/site-packages/torch/nn/modules/module.py:2441: UserWarning: for vision_model.encoder.layers.1.layer_norm1.bias: copying from a non-meta parameter in the checkpoint to a meta parameter in the current model, which is a no-op. (Did you mean to pass `assign=True` to assign items in the state dictionary to their corresponding key in the module instead of copying them in place?)
  warnings.warn(
/home/jeremy/code/SynDORBench/syndorb_env/lib/python3.10/site-packages/torch/nn/modules/module.py:2441: UserWarning: for vision_model.encoder.layers.1.mlp.fc1.weight: copying from a non-meta parameter in the checkpoint to a meta parameter in the current model, which is a no-op. (Did you mean to pass `assign=True` to assign items in the state dictionary to their corresponding key in the module instead of copying them in place?)
  warnings.warn(
/home/jeremy/code/SynDORBench/syndorb_env/lib/python3.10/site-packages/torch/nn/modules/module.py:2441: UserWarning: for vision_model.encoder.layers.1.mlp.fc1.bias: copying from a non-meta parameter in the checkpoint to a meta parameter in the current model, which is a no-op. (Did you mean to pass `assign=True` to assign items in the state dictionary to their corresponding key in the module instead of copying them in place?)
  warnings.warn(
/home/jeremy/code/SynDORBench/syndorb_env/lib/python3.10/site-packages/torch/nn/modules/module.py:2441: UserWarning: for vision_model.encoder.layers.1.mlp.fc2.weight: copying from a non-meta parameter in the checkpoint to a meta parameter in the current model, which is a no-op. (Did you mean to pass `assign=True` to assign items in the state dictionary to their corresponding key in the module instead of copying them in place?)
  warnings.warn(
/home/jeremy/code/SynDORBench/syndorb_env/lib/python3.10/site-packages/torch/nn/modules/module.py:2441: UserWarning: for vision_model.encoder.layers.1.mlp.fc2.bias: copying from a non-meta parameter in the checkpoint to a meta parameter in the current model, which is a no-op. (Did you mean to pass `assign=True` to assign items in the state dictionary to their corresponding key in the module instead of copying them in place?)
  warnings.warn(
/home/jeremy/code/SynDORBench/syndorb_env/lib/python3.10/site-packages/torch/nn/modules/module.py:2441: UserWarning: for vision_model.encoder.layers.1.layer_norm2.weight: copying from a non-meta parameter in the checkpoint to a meta parameter in the current model, which is a no-op. (Did you mean to pass `assign=True` to assign items in the state dictionary to their corresponding key in the module instead of copying them in place?)
  warnings.warn(
/home/jeremy/code/SynDORBench/syndorb_env/lib/python3.10/site-packages/torch/nn/modules/module.py:2441: UserWarning: for vision_model.encoder.layers.1.layer_norm2.bias: copying from a non-meta parameter in the checkpoint to a meta parameter in the current model, which is a no-op. (Did you mean to pass `assign=True` to assign items in the state dictionary to their corresponding key in the module instead of copying them in place?)
  warnings.warn(
/home/jeremy/code/SynDORBench/syndorb_env/lib/python3.10/site-packages/torch/nn/modules/module.py:2441: UserWarning: for vision_model.encoder.layers.2.self_attn.k_proj.weight: copying from a non-meta parameter in the checkpoint to a meta parameter in the current model, which is a no-op. (Did you mean to pass `assign=True` to assign items in the state dictionary to their corresponding key in the module instead of copying them in place?)
  warnings.warn(
/home/jeremy/code/SynDORBench/syndorb_env/lib/python3.10/site-packages/torch/nn/modules/module.py:2441: UserWarning: for vision_model.encoder.layers.2.self_attn.k_proj.bias: copying from a non-meta parameter in the checkpoint to a meta parameter in the current model, which is a no-op. (Did you mean to pass `assign=True` to assign items in the state dictionary to their corresponding key in the module instead of copying them in place?)
  warnings.warn(
/home/jeremy/code/SynDORBench/syndorb_env/lib/python3.10/site-packages/torch/nn/modules/module.py:2441: UserWarning: for vision_model.encoder.layers.2.self_attn.v_proj.weight: copying from a non-meta parameter in the checkpoint to a meta parameter in the current model, which is a no-op. (Did you mean to pass `assign=True` to assign items in the state dictionary to their corresponding key in the module instead of copying them in place?)
  warnings.warn(
/home/jeremy/code/SynDORBench/syndorb_env/lib/python3.10/site-packages/torch/nn/modules/module.py:2441: UserWarning: for vision_model.encoder.layers.2.self_attn.v_proj.bias: copying from a non-meta parameter in the checkpoint to a meta parameter in the current model, which is a no-op. (Did you mean to pass `assign=True` to assign items in the state dictionary to their corresponding key in the module instead of copying them in place?)
  warnings.warn(
/home/jeremy/code/SynDORBench/syndorb_env/lib/python3.10/site-packages/torch/nn/modules/module.py:2441: UserWarning: for vision_model.encoder.layers.2.self_attn.q_proj.weight: copying from a non-meta parameter in the checkpoint to a meta parameter in the current model, which is a no-op. (Did you mean to pass `assign=True` to assign items in the state dictionary to their corresponding key in the module instead of copying them in place?)
  warnings.warn(
/home/jeremy/code/SynDORBench/syndorb_env/lib/python3.10/site-packages/torch/nn/modules/module.py:2441: UserWarning: for vision_model.encoder.layers.2.self_attn.q_proj.bias: copying from a non-meta parameter in the checkpoint to a meta parameter in the current model, which is a no-op. (Did you mean to pass `assign=True` to assign items in the state dictionary to their corresponding key in the module instead of copying them in place?)
  warnings.warn(
/home/jeremy/code/SynDORBench/syndorb_env/lib/python3.10/site-packages/torch/nn/modules/module.py:2441: UserWarning: for vision_model.encoder.layers.2.self_attn.out_proj.weight: copying from a non-meta parameter in the checkpoint to a meta parameter in the current model, which is a no-op. (Did you mean to pass `assign=True` to assign items in the state dictionary to their corresponding key in the module instead of copying them in place?)
  warnings.warn(
/home/jeremy/code/SynDORBench/syndorb_env/lib/python3.10/site-packages/torch/nn/modules/module.py:2441: UserWarning: for vision_model.encoder.layers.2.self_attn.out_proj.bias: copying from a non-meta parameter in the checkpoint to a meta parameter in the current model, which is a no-op. (Did you mean to pass `assign=True` to assign items in the state dictionary to their corresponding key in the module instead of copying them in place?)
  warnings.warn(
/home/jeremy/code/SynDORBench/syndorb_env/lib/python3.10/site-packages/torch/nn/modules/module.py:2441: UserWarning: for vision_model.encoder.layers.2.layer_norm1.weight: copying from a non-meta parameter in the checkpoint to a meta parameter in the current model, which is a no-op. (Did you mean to pass `assign=True` to assign items in the state dictionary to their corresponding key in the module instead of copying them in place?)
  warnings.warn(

Model Class: LlavaQwenForCausalLM

In [4]:
import pandas as pd

day_path = '/mnt/harddisk/jeremy/synthetic_dataset_output/SynDORBench/index/human_detection/day.jsonl'
day_df = pd.read_json(day_path, lines=True)

print(day_df.loc[0, 'img_path'])

images/SMPLitex_texture_00000_choking_huge_landscape_noon_south_10.8/run_pose-06-hangon-kaiwa_stageii_frame_780.npz_20250907_220206/raw_images/frame0001_cam000_r10_phi0.0_theta0.0.jpg

In [11]:
from pathlib import Path

time_instruction = f"This is 1 video frame from from a surveillance footage."

perspective_prompt = "You are seeing this image from a surveillance camera view and you are the surveillance camera. What action is the person performing?"
task_prompt = "Describe in details what you see from the video frame."

dataset_dir = Path("/mnt/harddisk/jeremy/synthetic_dataset_output/SynDORBench/")
picture_path = Path("images/SMPLitex_texture_00000_choking_huge_landscape_noon_south_10.8/run_pose-06-hangon-kaiwa_stageii_frame_780.npz_20250907_220206/raw_images/frame0001_cam000_r10_phi0.0_theta0.0.jpg")

abs_picture_path = dataset_dir / picture_path

actual_path = '/mnt/harddisk/jeremy/synthetic_dataset_output/SynDORBench/images/SMPLitex_texture_00000_choking_huge_landscape_noon_south_10.8/run_pose-06-hangon-kaiwa_stageii_frame_780.npz_20250907_220206/raw_images/frame0001_cam000_r10_phi0.0_theta0.0.jpg'


print(actual_path)
print(str(abs_picture_path))
print(actual_path == str(abs_picture_path))

base_text = f"\n{time_instruction}\n{perspective_prompt} {task_prompt}"

print(model.predict(actual_path, base_text))

/mnt/harddisk/jeremy/synthetic_dataset_output/SynDORBench/images/SMPLitex_texture_00000_choking_huge_landscape_noon_south_10.8/run_pose-06-hangon-kaiwa_stageii_frame_780.npz_20250907_220206/raw_images/frame0001_cam000_r10_phi0.0_theta0.0.jpg
/mnt/harddisk/jeremy/synthetic_dataset_output/SynDORBench/images/SMPLitex_texture_00000_choking_huge_landscape_noon_south_10.8/run_pose-06-hangon-kaiwa_stageii_frame_780.npz_20250907_220206/raw_images/frame0001_cam000_r10_phi0.0_theta0.0.jpg
True
In the video frame, I see a person standing in shallow water, facing away from the camera. The person appears to be looking out over a landscape that includes trees and possibly a body of water. The lighting suggests it might be early morning or late afternoon, given the softness of the light. There is no visible movement or action being performed by the person, such as walking or swimming, which indicates they are likely just observing the surroundings.

In [13]:
day_df.head()

,source_dir,action,scene,lighting,radius,smplx_texture,img_path,mask_path,img_name,nv_path,human_discernable,prompt,task
0,SMPLitex_texture_00000_choking_huge_landscape_...,choking,huge_landscape,noon_south,10.8,SMPLitex-texture-00000,images/SMPLitex_texture_00000_choking_huge_lan...,images/SMPLitex_texture_00000_choking_huge_lan...,frame0001_cam000_r10_phi0.0_theta0.0.jpg,NaN,1,Respond only with 1 or 0. Respond with 1 if a ...,human_detection
1,SMPLitex_texture_00000_choking_huge_landscape_...,choking,huge_landscape,noon_south,10.8,SMPLitex-texture-00000,images/SMPLitex_texture_00000_choking_huge_lan...,images/SMPLitex_texture_00000_choking_huge_lan...,frame0001_cam001_r10_phi0.0_theta22.5.jpg,NaN,1,Respond only with 1 or 0. Respond with 1 if a ...,human_detection
2,SMPLitex_texture_00000_choking_huge_landscape_...,choking,huge_landscape,noon_south,10.8,SMPLitex-texture-00000,images/SMPLitex_texture_00000_choking_huge_lan...,images/SMPLitex_texture_00000_choking_huge_lan...,frame0001_cam002_r10_phi0.0_theta45.0.jpg,NaN,1,Respond only with 1 or 0. Respond with 1 if a ...,human_detection
3,SMPLitex_texture_00000_choking_huge_landscape_...,choking,huge_landscape,noon_south,10.8,SMPLitex-texture-00000,images/SMPLitex_texture_00000_choking_huge_lan...,images/SMPLitex_texture_00000_choking_huge_lan...,frame0001_cam003_r10_phi0.0_theta67.5.jpg,NaN,1,Respond only with 1 or 0. Respond with 1 if a ...,human_detection
4,SMPLitex_texture_00000_choking_huge_landscape_...,choking,huge_landscape,noon_south,10.8,SMPLitex-texture-00000,images/SMPLitex_texture_00000_choking_huge_lan...,images/SMPLitex_texture_00000_choking_huge_lan...,frame0001_cam004_r10_phi45.0_theta0.0.jpg,NaN,1,Respond only with 1 or 0. Respond with 1 if a ...,human_detection

In [ ]:

def get_inference_from_df(model, df, root_dir="", limit=5):
    results = []

    # for prototyping, limit to head
    if limit:
        df = df.head(limit)
    
    for i in range(len(df)):
        img_path = df.loc[i, 'img_path']
        task_prompt = df.loc[i, 'prompt']
        if root_dir:
            img_path = root_dir / img_path
            
        pred = model.predict(img_path, task_prompt) 
        

        results.append({
            "img_path": img_path,
            "task_prompt": task_prompt,
            "prediction": pred
        })
    return pd.DataFrame(results)


small_df = day_df.head(100)
result_df = get_inference_from_df(model, small_df, root_dir=dataset_dir)

/home/jeremy/code/SynDORBench/syndorb_env/lib/python3.10/site-packages/transformers/generation/configuration_utils.py:492: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/jeremy/code/SynDORBench/syndorb_env/lib/python3.10/site-packages/transformers/generation/configuration_utils.py:497: UserWarning: `do_sample` is set to `False`. However, `top_p` is set to `0.8` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`.
  warnings.warn(
/home/jeremy/code/SynDORBench/syndorb_env/lib/python3.10/site-packages/transformers/generation/configuration_utils.py:509: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `20` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

In [19]:
result_df

,img_path,task_prompt,prediction
0,/mnt/harddisk/jeremy/synthetic_dataset_output/...,Respond only with 1 or 0. Respond with 1 if a ...,1
1,/mnt/harddisk/jeremy/synthetic_dataset_output/...,Respond only with 1 or 0. Respond with 1 if a ...,1
2,/mnt/harddisk/jeremy/synthetic_dataset_output/...,Respond only with 1 or 0. Respond with 1 if a ...,1
3,/mnt/harddisk/jeremy/synthetic_dataset_output/...,Respond only with 1 or 0. Respond with 1 if a ...,0
4,/mnt/harddisk/jeremy/synthetic_dataset_output/...,Respond only with 1 or 0. Respond with 1 if a ...,1
...,...,...,...
95,/mnt/harddisk/jeremy/synthetic_dataset_output/...,Respond only with 1 or 0. Respond with 1 if a ...,1
96,/mnt/harddisk/jeremy/synthetic_dataset_output/...,Respond only with 1 or 0. Respond with 1 if a ...,0
97,/mnt/harddisk/jeremy/synthetic_dataset_output/...,Respond only with 1 or 0. Respond with 1 if a ...,1
98,/mnt/harddisk/jeremy/synthetic_dataset_output/...,Respond only with 1 or 0. Respond with 1 if a ...,1
99,/mnt/harddisk/jeremy/synthetic_dataset_output/...,Respond only with 1 or 0. Respond with 1 if a ...,0